CHECKPOINT_DIR = "../../llama/llama-2-7b-chat/"
TOKENIZER_PATH = "../../llama/tokenizer.model"
MAX_SEQ_LEN = 8192
MAX_BATCH_SIZE = 8
MODEL_PARALLEL_SIZE = 1

TEMPERATURE = 1
TOP_P = 0.9
MAX_GEN_LEN = 8192
HOST = "0.0.0.0"
PORT = 8080
